import { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  {
    id: 'pushups',
    name: 'Push-Ups',
    muscle: 'Chest',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Hands under shoulders, body in a straight line. Lower until chest nearly touches the floor, then press up.',
    caloriesPerMin: 8,
    focus: ['push', 'full', 'upper'],
  },
  {
    id: 'squats',
    name: 'Bodyweight Squats',
    muscle: 'Quads',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 15,
    instructions: 'Feet shoulder-width. Sit hips back and down, chest up. Drive through heels to stand.',
    caloriesPerMin: 8,
    focus: ['legs', 'full', 'lower'],
  },
  {
    id: 'lunges',
    name: 'Walking Lunges',
    muscle: 'Legs',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Step forward, drop the back knee toward the floor. Drive up and switch legs.',
    caloriesPerMin: 9,
    focus: ['legs', 'lower'],
  },
  {
    id: 'plank',
    name: 'Forearm Plank',
    muscle: 'Core',
    equipment: 'any',
    type: 'time',
    defaultSets: 3,
    defaultSeconds: 40,
    instructions: 'Elbows under shoulders, squeeze glutes and brace abs. Keep hips level.',
    caloriesPerMin: 5,
    focus: ['core', 'full'],
  },
  {
    id: 'mountain',
    name: 'Mountain Climbers',
    muscle: 'Core',
    equipment: 'any',
    type: 'time',
    defaultSets: 3,
    defaultSeconds: 30,
    instructions: 'High plank. Drive knees toward chest alternately at a controlled sprint pace.',
    caloriesPerMin: 11,
    focus: ['cardio', 'core', 'full'],
  },
  {
    id: 'burpees',
    name: 'Burpees',
    muscle: 'Full Body',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'Squat, plant hands, jump feet back, push-up optional, jump feet in, explode up.',
    caloriesPerMin: 12,
    focus: ['cardio', 'full'],
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridges',
    muscle: 'Glutes',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 15,
    instructions: 'Lie on back, feet planted. Drive hips up, squeeze glutes at the top, lower slowly.',
    caloriesPerMin: 6,
    focus: ['legs', 'lower', 'posterior'],
  },
  {
    id: 'superman',
    name: 'Superman Holds',
    muscle: 'Back',
    equipment: 'any',
    type: 'time',
    defaultSets: 3,
    defaultSeconds: 25,
    instructions: 'Lie face down. Lift chest, arms and legs off the floor. Hold, then lower.',
    caloriesPerMin: 5,
    focus: ['pull', 'posterior', 'upper'],
  },
  {
    id: 'bicycle',
    name: 'Bicycle Crunches',
    muscle: 'Core',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 20,
    instructions: 'Hands behind head. Bring opposite elbow to opposite knee in a smooth rotation.',
    caloriesPerMin: 7,
    focus: ['core'],
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    muscle: 'Cardio',
    equipment: 'any',
    type: 'time',
    defaultSets: 3,
    defaultSeconds: 40,
    instructions: 'Jump feet out while raising arms overhead, then return. Keep a light bounce.',
    caloriesPerMin: 10,
    focus: ['cardio', 'full'],
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    muscle: 'Quads',
    equipment: 'any',
    type: 'time',
    defaultSets: 3,
    defaultSeconds: 35,
    instructions: 'Back against wall, slide down until thighs are parallel. Hold without leaning on knees.',
    caloriesPerMin: 6,
    focus: ['legs', 'lower'],
  },
  {
    id: 'calf-raise',
    name: 'Calf Raises',
    muscle: 'Calves',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 18,
    instructions: 'Rise onto the balls of your feet, pause, then lower with control.',
    caloriesPerMin: 5,
    focus: ['legs', 'lower'],
  },
  {
    id: 'dips',
    name: 'Chair Dips',
    muscle: 'Triceps',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'Hands on a sturdy chair behind you. Lower until elbows hit ~90°, then press up.',
    caloriesPerMin: 7,
    focus: ['push', 'upper'],
  },
  {
    id: 'pike-push',
    name: 'Pike Push-Ups',
    muscle: 'Shoulders',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 8,
    instructions: 'Hips high in a pike. Bend elbows to lower the crown of your head toward the floor.',
    caloriesPerMin: 7,
    focus: ['push', 'upper'],
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    muscle: 'Cardio',
    equipment: 'any',
    type: 'time',
    defaultSets: 3,
    defaultSeconds: 30,
    instructions: 'Run in place driving knees to hip height. Pump the arms and stay light on your feet.',
    caloriesPerMin: 11,
    focus: ['cardio', 'full'],
  },
  {
    id: 'jump-squat',
    name: 'Jump Squats',
    muscle: 'Legs',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'Squat down, then explode upward. Land softly and go straight into the next rep.',
    caloriesPerMin: 11,
    focus: ['legs', 'cardio', 'lower'],
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    muscle: 'Obliques',
    equipment: 'any',
    type: 'time',
    defaultSets: 2,
    defaultSeconds: 25,
    instructions: 'Stack feet, elbow under shoulder. Lift hips so the body forms a straight line. Switch sides.',
    caloriesPerMin: 5,
    focus: ['core'],
  },
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunges',
    muscle: 'Legs',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Step back into a lunge, front knee stacked over ankle. Drive through the front heel.',
    caloriesPerMin: 8,
    focus: ['legs', 'lower'],
  },
  {
    id: 'inchworm',
    name: 'Inchworms',
    muscle: 'Full Body',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 8,
    instructions: 'Hinge, walk hands out to a plank, pause, walk hands back and stand tall.',
    caloriesPerMin: 7,
    focus: ['full', 'core', 'mobility'],
  },
  {
    id: 'bird-dog',
    name: 'Bird Dogs',
    muscle: 'Core',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'On all fours, extend opposite arm and leg. Pause, then switch. Keep hips square.',
    caloriesPerMin: 4,
    focus: ['core', 'mobility', 'posterior'],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bugs',
    muscle: 'Core',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'On your back, arms up, knees at 90°. Extend opposite arm and leg without arching.',
    caloriesPerMin: 4,
    focus: ['core', 'mobility'],
  },
  {
    id: 'hip-hinge',
    name: 'Good Mornings',
    muscle: 'Hamstrings',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Soft knees, hinge at the hips with a flat back until you feel a hamstring stretch. Stand tall.',
    caloriesPerMin: 5,
    focus: ['posterior', 'legs', 'lower'],
  },
  {
    id: 'db-row',
    name: 'Dumbbell Rows',
    muscle: 'Back',
    equipment: 'home',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Hinge, pull the weight to your hip, squeeze the shoulder blade, lower slowly.',
    caloriesPerMin: 7,
    focus: ['pull', 'upper', 'posterior'],
  },
  {
    id: 'goblet',
    name: 'Goblet Squats',
    muscle: 'Quads',
    equipment: 'home',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Hold a dumbbell at your chest. Squat deep with elbows inside the knees.',
    caloriesPerMin: 8,
    focus: ['legs', 'lower', 'full'],
  },
  {
    id: 'db-press',
    name: 'Shoulder Press',
    muscle: 'Shoulders',
    equipment: 'home',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'Press dumbbells overhead without flaring ribs. Lower to ear height.',
    caloriesPerMin: 7,
    focus: ['push', 'upper'],
  },
  {
    id: 'curls',
    name: 'Bicep Curls',
    muscle: 'Biceps',
    equipment: 'home',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Elbows pinned to sides. Curl without swinging. Squeeze at the top.',
    caloriesPerMin: 5,
    focus: ['pull', 'upper'],
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlifts',
    muscle: 'Hamstrings',
    equipment: 'home',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'Soft knees, push hips back, slide weights down the thighs. Stand by driving hips forward.',
    caloriesPerMin: 7,
    focus: ['posterior', 'legs', 'lower'],
  },
  {
    id: 'lateral',
    name: 'Lateral Raises',
    muscle: 'Shoulders',
    equipment: 'home',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Raise arms to just below shoulder height with a slight elbow bend. Control the descent.',
    caloriesPerMin: 5,
    focus: ['push', 'upper'],
  },
  {
    id: 'floor-press',
    name: 'Floor Press',
    muscle: 'Chest',
    equipment: 'home',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'Lie on the floor, press dumbbells up. Lower until triceps kiss the floor, then press.',
    caloriesPerMin: 6,
    focus: ['push', 'upper'],
  },
  {
    id: 'band-pull',
    name: 'Band Pull-Aparts',
    muscle: 'Rear Delts',
    equipment: 'home',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 15,
    instructions: 'Arms straight, pull a band apart until it touches your chest. Squeeze shoulder blades.',
    caloriesPerMin: 4,
    focus: ['pull', 'upper', 'posterior'],
  },
  {
    id: 'bench',
    name: 'Barbell Bench Press',
    muscle: 'Chest',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 4,
    defaultReps: 8,
    instructions: 'Retract scapula, lower the bar to mid-chest, press up without bouncing.',
    caloriesPerMin: 7,
    focus: ['push', 'upper'],
  },
  {
    id: 'pulldown',
    name: 'Lat Pulldown',
    muscle: 'Lats',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 4,
    defaultReps: 10,
    instructions: 'Pull the bar to your upper chest, elbows down and back. Control the return.',
    caloriesPerMin: 6,
    focus: ['pull', 'upper'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    muscle: 'Quads',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 4,
    defaultReps: 12,
    instructions: 'Feet mid-platform. Lower until knees near 90°, then drive through the whole foot.',
    caloriesPerMin: 8,
    focus: ['legs', 'lower'],
  },
  {
    id: 'cable-row',
    name: 'Seated Cable Row',
    muscle: 'Back',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 4,
    defaultReps: 10,
    instructions: 'Tall torso, pull handle to the navel, squeeze mid-back, then extend with control.',
    caloriesPerMin: 6,
    focus: ['pull', 'upper', 'posterior'],
  },
  {
    id: 'ohp',
    name: 'Overhead Press',
    muscle: 'Shoulders',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 4,
    defaultReps: 8,
    instructions: 'Brace core, press the bar overhead in a straight line. Lock out without leaning back.',
    caloriesPerMin: 7,
    focus: ['push', 'upper'],
  },
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    muscle: 'Posterior',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 4,
    defaultReps: 5,
    instructions: 'Bar over mid-foot, hinge and grip. Drive the floor away and lock hips. Lower with control.',
    caloriesPerMin: 9,
    focus: ['posterior', 'legs', 'full', 'pull'],
  },
  {
    id: 'leg-curl',
    name: 'Lying Leg Curl',
    muscle: 'Hamstrings',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Curl the pad toward your glutes without lifting hips. Slow negative.',
    caloriesPerMin: 5,
    focus: ['legs', 'posterior', 'lower'],
  },
  {
    id: 'face-pull',
    name: 'Face Pulls',
    muscle: 'Rear Delts',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 15,
    instructions: 'Pull the rope to your face, externally rotate so fists end by your ears.',
    caloriesPerMin: 4,
    focus: ['pull', 'upper', 'posterior'],
  },
  {
    id: 'cable-fly',
    name: 'Cable Flyes',
    muscle: 'Chest',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 12,
    instructions: 'Slight elbow bend. Sweep hands together in an arc and squeeze the chest.',
    caloriesPerMin: 5,
    focus: ['push', 'upper'],
  },
  {
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    muscle: 'Quads',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 4,
    defaultReps: 8,
    instructions: 'Bar on upper back, brace, sit between the hips. Drive up without collapsing knees in.',
    caloriesPerMin: 9,
    focus: ['legs', 'lower', 'full'],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrusts',
    muscle: 'Glutes',
    equipment: 'gym',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'Upper back on a bench, bar over hips. Drive through heels until torso is parallel.',
    caloriesPerMin: 7,
    focus: ['legs', 'posterior', 'lower'],
  },
  {
    id: 'kb-swing',
    name: 'Kettlebell Swings',
    muscle: 'Posterior',
    equipment: 'home',
    type: 'reps',
    defaultSets: 4,
    defaultReps: 15,
    instructions: 'Hinge hard, snap the hips to float the bell to chest height. This is a hip snap, not a squat.',
    caloriesPerMin: 11,
    focus: ['cardio', 'posterior', 'full'],
  },
  {
    id: 'farmer',
    name: 'Farmer Carries',
    muscle: 'Grip',
    equipment: 'home',
    type: 'time',
    defaultSets: 3,
    defaultSeconds: 40,
    instructions: 'Stand tall with heavy weights at your sides. Walk slow and proud, no leaning.',
    caloriesPerMin: 8,
    focus: ['full', 'core'],
  },
  {
    id: 'shadowbox',
    name: 'Shadow Boxing',
    muscle: 'Cardio',
    equipment: 'any',
    type: 'time',
    defaultSets: 4,
    defaultSeconds: 45,
    instructions: 'Light bounce, jab-cross-hook combinations. Keep hands up and breathe through the mouth.',
    caloriesPerMin: 10,
    focus: ['cardio', 'full'],
  },
  {
    id: 'step-up',
    name: 'Step-Ups',
    muscle: 'Legs',
    equipment: 'any',
    type: 'reps',
    defaultSets: 3,
    defaultReps: 10,
    instructions: 'Step onto a sturdy surface, drive through the whole foot, control the descent.',
    caloriesPerMin: 8,
    focus: ['legs', 'lower'],
  },
  {
    id: 'hollow',
    name: 'Hollow Body Hold',
    muscle: 'Core',
    equipment: 'any',
    type: 'time',
    defaultSets: 3,
    defaultSeconds: 25,
    instructions: 'Lower back glued to the floor, arms and legs long and hovering. Tiny hollow shape.',
    caloriesPerMin: 5,
    focus: ['core'],
  },
];

export function exercisesFor(equipment: 'none' | 'home' | 'gym', focus?: string): Exercise[] {
  return EXERCISES.filter((e) => {
    const equipOk =
      e.equipment === 'any' ||
      e.equipment === equipment ||
      (equipment === 'gym' && e.equipment === 'home') ||
      (equipment === 'home' && e.equipment === 'none');
    const focusOk = !focus || e.focus.includes(focus);
    return equipOk && focusOk;
  });
}
